### PR TITLE
Feature/client side chat impl

### LINKED ISSUE #31: Implement Chat Functionality
(dream feature)

### PR DESCRIPTION
**Pull request by stephengrice**
Closes #31 

Be sure to merge #66 first

### CODE REVIEW

**Comment by stephengrice** [comment]
@KenDJohnson 

Rachel and I added PMs just now. It works for "Everyone" but for just sending to one of the players, I get:

```
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "/home/steve/wkdir/flask-production/clueless/__main__.py", line 42, in websockopen
    await player.user_loop()
  File "/home/steve/wkdir/flask-production/clueless/state.py", line 192, in user_loop
    await self.dispatch_message(msg)
  File "/home/steve/wkdir/flask-production/clueless/state.py", line 168, in dispatch_message
    await self.game_action(lambda game: game.chat(self, message), "send a chat message")
  File "/home/steve/wkdir/flask-production/clueless/state.py", line 107, in game_action
    await action(self.game)
  File "/home/steve/wkdir/flask-production/clueless/state.py", line 516, in chat
    to_player = self.players[chat.to]
TypeError: list indices must be integers or slices, not str
```

Thoughts?

**Comment by stephengrice** [comment]
Maybe `to_player = self.players[chat.to]` can change to `to_player = self.players[int(chat.to)]`

**Comment by KenDJohnson** [comment]
> Rachel and I added PMs just now. It works for "Everyone" but for just sending to one of the players, I get:

```
        gameHub.sendChat(this.txtChat.value, $('#selectRecipient').val());
```
I think the issue is here (JS is not my strong suit, so I'm not entirely sure), but it seems to be sending `"1"` instead of `1`. So converting to an int on the backend works, but ideally would be done on the client as well.

**Comment by stephengrice** [comment]
Edit: Deleted error, I was running a version of the server from another branch and fixed another minor error

Agreed that a fix on both sides would be ideal, feel free to update the server on this branch, otherwise this should be good to merge.

**Comment by stephengrice** [comment]
@KenDJohnson can you double check that `private` is getting set on the message you're sending? From what I can tell, private messages are properly delivered to just one user, but `private` is not set.

Edit: wait this may be clientside

**Comment by stephengrice** [comment]
@KenDJohnson Should be working, merge when ready. Also it will break when merged due to changes on the other branch. I didn't want to clutter this branch by merging. I left the line that will work in there as a comment, I'll write an issue so we dont forget to fix.

**Pull request merged**
