### PR TITLE
Draft: Feature/more clientside

### PR DESCRIPTION
**Pull request by stephengrice**
Rachel and I created wireframe diagrams of the UI. This pull request is implementing that design. Merged #18 before starting.

Update 11/14: Looking good. We have most panels implemented. Need to fill in remaining panels, add button handlers, and then handle all remaining server messages. Then we should be done.

**Panel Implementation**

- [x] Fill in NotepadPanel

- [x] Fill in ChatPanel

- [x] Fill in MovePanel

- [x] Fill in SuggestPanel

- [x] Fill in AccusePanel

- [x] Fix modal display issue on screen 3

**Messages to Send**

- [x] CreateGame

- [x] JoinGame

- [x] Move

- [x] Suggest

- [x] Accuse

- [x] Chat

**Messages to Receive**

- [x] Joined

- [x] Registration

- [x] Position

- [x] SuggestionWitness

- [x] SuggestionStatus

- [x] Accusation

- [x] Winner

- [x] Disqualified

- [x] Witness

- [x] ServerChat

**Display Updates**

- [x] Fix panel display issues

**Integration Notes**

- [x] Change Joined to UserJoined

- [x] Figure out why Disqualified is showing up

- [x] Add support for multiple modals (queue) (Toast instead of modal)

- [x] Change WitnessItem message to Witness

- [x] Disable buttons when it is not your turn.

- [x] Add visual indicator of localPlayer

- [x] Do not hard code localhost for websocket uri

### CODE REVIEW

**Comment by KenDJohnson** [comment]
What's the status on this? Are you still working of this PR? Should this be reviewed or closed out?

**Comment by stephengrice** [comment]
No need to review yet. This is our main working branch. Still in progress. The checkboxes are pretty accurate as far as what's left.

**Comment by stephengrice** [comment]
Closed some of these items to new issue #27 (push to target)

**Comment by stephengrice** [comment]
Superseded by feature/minimal-integration

**Pull request closed without merging**
