### PR TITLE
feature/protobuf-impl

### PR DESCRIPTION
**Pull request by KenDJohnson**
Added a [protobuf](https://developers.google.com/protocol-buffers) implementation of the messages and generated code for both python and javascript.

Thinking this should cover all the "over the wire" stuff, we'll probably need some minimal wrappers for internal logic.

This is a draft PR, still need to get the protobuf runtime modules imported on both client and server, and the requirements set up in the Pipfile/package.json.

### CODE REVIEW

**Comment by KenDJohnson** [comment]
Then on both sides, the psuedocode for handling messages would be:

```
func on_ws_recv(data):
  message = protobuf.decode(data)
  dispatch_message(message)

func dispatch_message(msg):
  if msg is Accuse:
    handle_accuse(msg)
  if msg is Suggest:
    handle_suggest(msg)
  ...
```

**Review by stephengrice — APPROVED** [review]
Awesome. This is going to make things much easier. Also very happy that we're committing the generated files instead of trying to gitignore them somehow.

**Comment by KenDJohnson** [comment]
> Awesome. This is going to make things much easier. Also very happy that we're committing the generated files instead of trying to gitignore them somehow.

Yeah once merged the generated files should be more or less "one and done" so I think it makes sense to check them in.

**Review by KevinKYeh — APPROVED** [review]

**Review by nguyen-jhu — APPROVED** [review]
Looks good, aligns with SRS stated messages

**Pull request merged**
